spring:
  datasource:
    url: jdbc:h2:mem:cca_dev
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true

# Logging
logging:
  level:
    org.springframework.security: INFO
    com.caracore.cca: DEBUG
    org.hibernate.SQL: DEBUG
