# Configurações para ambiente de TESTES
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recria o schema para cada teste
    show-sql: false  # Desabilitado para não poluir logs de teste
    properties:
      hibernate:
        '[format_sql]': false
        '[use_sql_comments]': false
        '[generate_statistics]': false
        '[dialect]': org.hibernate.dialect.H2Dialect
  
  # H2 Console para debug nos testes
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Cache desabilitado para testes
  cache:
    type: none
  
  # Security sem debug nos testes
  security:
    debug: false
  
  # Flyway desabilitado para testes (usando create-drop)
  flyway:
    enabled: false

# Logging mínimo para testes
logging:
  level:
    root: WARN
    '[org.springframework.security]': WARN
    '[org.springframework.web]': WARN
    '[com.caracore.cca]': INFO
    '[org.hibernate.SQL]': WARN
    '[USER_ACTIVITY]': WARN
  
# Swagger desabilitado para testes
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Configurações específicas da aplicação para testes
cca:
  ambiente: teste
  debug-mode: false
  mock-external-services: true  # Sempre usar mocks nos testes
  whatsapp:
    api-url: http://localhost:3000/mock
    api-key: test-api-key
    enabled: false
  email:
    smtp:
      host: localhost
      port: 2525
      username: test
      password: test
    from: test@test.com
  security:
    jwt:
      secret: test-secret-key-for-testing-only
      expiration: 3600000  # 1 hora

# Configuração do reCAPTCHA para ambiente de teste
recaptcha:
  enabled: false  # Desabilitado para testes
  secret: ""
  site-key: ""
  verify-url: "https://www.google.com/recaptcha/api/siteverify"

# Configurações do servidor para testes
server:
  port: 0  # Porta aleatória para evitar conflitos
  servlet:
    session:
      timeout: 10m
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: true

# Configurações de teste específicas
test:
  database:
    cleanup-strategy: truncate  # Limpar dados entre testes
  mock:
    external-services: true
  timeout:
    default: 10s
    integration: 30s
