# Configurações para ambiente LOCAL com PostgreSQL
# Para usar este perfil: mvn spring-boot:run -Dspring.profiles.active=local

# Configurações do servidor
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    session:
      timeout: 60m  # 1 hora para desenvolvimento
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

spring:
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/cca_db
    username: cca_user
    password: cca_password
    driver-class-name: org.postgresql.Driver
    hikari:
      # Pool de conexões para desenvolvimento local
      maximum-pool-size: 15        # Máximo de conexões simultâneas
      minimum-idle: 5              # Mínimo de conexões ociosas
      connection-timeout: 30000    # Timeout para obter conexão (30s)
      idle-timeout: 600000         # Timeout para conexão ociosa (10min)
      max-lifetime: 1800000        # Tempo máximo de vida da conexão (30min)
      leak-detection-threshold: 60000  # Detectar vazamento de conexão (60s)
      pool-name: CCA-Local-Pool
      # Configurações de validação
      validation-timeout: 5000     # Timeout para validação (5s)
      connection-test-query: SELECT 1
      auto-commit: false           # Controle manual de transações
      # Configurações de inicialização
      connection-init-sql: "SET search_path TO public"
      # Configurações de performance
      register-mbeans: true        # Monitoramento JMX
      allow-pool-suspension: false
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Cria e remove o schema para desenvolvimento local
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          '[time_zone]': America/Sao_Paulo
        '[format_sql]': true
        '[use_sql_comments]': true
        '[generate_statistics]': false
        '[dialect]': org.hibernate.dialect.PostgreSQLDialect
  
  # Configurações de internacionalização
  web:
    locale: pt_BR
    locale-resolver: fixed
  
  # H2 Console desabilitado (usando PostgreSQL)
  h2:
    console:
      enabled: false
  
  # DevTools habilitado para desenvolvimento
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # Cache desabilitado para desenvolvimento
  cache:
    type: none
  
  # Flyway habilitado para migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
  
  # Desabilitar inicialização automática de scripts SQL
  sql:
    init:
      mode: never

# Logging detalhado para desenvolvimento local
logging:
  level:
    root: INFO
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG
    '[com.caracore.cca]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[USER_ACTIVITY]': INFO
  
# Swagger habilitado para desenvolvimento local
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true

# Configurações específicas da aplicação para desenvolvimento local
cca:
  ambiente: local
  debug-mode: true
  mock-external-services: false  # Usar serviços reais para testes locais
  whatsapp:
    api-url: ${WHATSAPP_API_URL:http://localhost:3000/api}
    api-key: ${WHATSAPP_API_KEY:local-test-key}
    enabled: ${WHATSAPP_ENABLED:true}
  email:
    smtp:
      host: ${SMTP_HOST:localhost}
      port: ${SMTP_PORT:1025}  # MailHog ou similar para desenvolvimento
      username: ${SMTP_USERNAME:test}
      password: ${SMTP_PASSWORD:test}
    from: ${EMAIL_FROM:noreply@local.dev}
  security:
    jwt:
      secret: ${JWT_SECRET:local-development-secret-key-change-in-production}
      expiration: 86400000  # 24 horas

# Configurações do reCAPTCHA para ambiente local
recaptcha:
  enabled: false  # Desabilitado para desenvolvimento local
  secret: ""
  site-key: ""
  verify-url: "https://www.google.com/recaptcha/api/siteverify"

# Monitoramento e métricas para desenvolvimento
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans
  endpoint:
    health:
      show-details: always  # Mostrar detalhes de saúde em desenvolvimento
  info:
    env:
      enabled: true
