server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cca_db
    driver-class-name: org.postgresql.Driver
    username: cca_user
    password: cca_password
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    debug: true
logging:
  level:
    org.springframework.security: DEBUG
    com.caracore.cca: DEBUG
    org.hibernate.SQL: DEBUG
    USER_ACTIVITY: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/user-activity.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/archived/user-activity-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30
spring.sql.init.mode: never
# Para evitar execução dupla de scripts em ambiente de teste, descomente a linha acima se necessário.