# Configuração padrão do aplicativo
# Esse arquivo define configurações globais que serão usadas em todos os perfis

spring:
  # Configuração global do Flyway - desabilitado por padrão
  flyway:
    enabled: false
    baseline-on-migrate: true
    # Os perfis específicos ativam e configuram o Flyway conforme necessário

  jackson:
    serialization:
      '[WRITE_DATES_AS_TIMESTAMPS]': false
      indent-output: true
    deserialization:
      '[FAIL_ON_UNKNOWN_PROPERTIES]': false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  web:
    resources:
      add-mappings: true

# Configurações de logging
logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    com.caracore: INFO

# Configurações do Google reCAPTCHA
google:
  recaptcha:
    site-key: ${RECAPTCHA_SITE_KEY:your-site-key-here}  # Chave do site fornecida pelo Google
    secret-key: ${RECAPTCHA_SECRET_KEY:your-secret-key-here}  # Chave secreta fornecida pelo Google

# Configurações de Feature Flags e A/B Testing
cca:
  feature-flags:
    # Controle do fluxo de agendamento
    multi-step-flow:
      enabled: true  # true = multi-etapas habilitado, false = apenas página única
    
    # Configurações de A/B Testing
    ab-testing:
      enabled: false  # true = ativa teste A/B entre fluxos
      multi-step-percentage: 50  # Porcentagem de usuários que verão fluxo multi-etapas (0-100)
    
    # Modo debug para desenvolvimento
    debug-mode: false  # true = permite forçar fluxos e logs detalhados
