# Configurações para ambiente DEV (Desenvolvimento)
# Para usar este perfil: mvn spring-boot:run -Dspring.profiles.active=dev

# Configurações do servidor
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    session:
      timeout: 30m
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

spring:
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cca_dev}
    username: ${DB_USERNAME:cca_user}
    password: ${DB_PASSWORD:cca_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate  # Usar apenas migrations em dev
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          '[time_zone]': America/Sao_Paulo
        '[format_sql]': false
        '[use_sql_comments]': false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Configurações de internacionalização
  web:
    locale: pt_BR
    locale-resolver: fixed
  
  # DevTools desabilitado em dev
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  
  # Cache habilitado para melhor performance
  cache:
    type: simple
  
  # Flyway habilitado para migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
  
  # Inicialização controlada do banco
  sql:
    init:
      mode: never  # Não executar scripts automáticos em dev

# Logging otimizado para desenvolvimento
logging:
  level:
    root: INFO
    '[org.springframework.security]': WARN
    '[org.springframework.web]': WARN
    '[com.caracore.cca]': INFO
    '[org.hibernate.SQL]': WARN
    '[USER_ACTIVITY]': INFO
  
# Swagger habilitado para desenvolvimento
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true

# Configurações específicas da aplicação para desenvolvimento
cca:
  ambiente: dev
  debug-mode: false
  mock-external-services: false
  whatsapp:
    api-url: ${WHATSAPP_API_URL:https://api.whatsapp.dev}
    api-key: ${WHATSAPP_API_KEY}
    enabled: ${WHATSAPP_ENABLED:true}
  email:
    smtp:
      host: ${SMTP_HOST:smtp.dev.example.com}
      port: ${SMTP_PORT:587}
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
    from: ${EMAIL_FROM:noreply@dev.caracore.com}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 43200000  # 12 horas

# Configuração do reCAPTCHA para ambiente dev
recaptcha:
  enabled: false  # Desabilitado para desenvolvimento
  secret: ${RECAPTCHA_SECRET_KEY:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}  # Chave de teste do Google
  site-key: ${RECAPTCHA_SITE_KEY:6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}  # Chave de teste do Google
  verify-url: "https://www.google.com/recaptcha/api/siteverify"

# Monitoramento limitado em dev
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
