# Configuration for H2 in-memory database mode
# Para usar este perfil: mvn spring-boot:run -Dspring.profiles.active=h2

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    session:
      timeout: 60m  # 1 hour for development
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always

# Spring configuration
spring:
  main:
    allow-bean-definition-overriding: true
    
  # H2 database configuration  
  datasource:
    url: jdbc:h2:mem:cca_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 console for browser-based database access
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false  # Change to true if you want remote access
  
  # Configuração do Flyway para H2
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: false
    
  # Desabilitar inicialização SQL para H2 (usaremos Flyway)
  sql:
    init:
      mode: never
  
  # JPA/Hibernate configuration - deixar Flyway gerenciar completamente
  jpa:
    hibernate:
      ddl-auto: none  # Flyway creates and manages schema completely
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.H2Dialect

  # MVC configuration
  mvc:
    static-path-pattern: /static/**
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd'T'HH:mm:ss

# Logging configuration for development
logging:
  level:
    "[org.springframework]": INFO
    "[com.caracore.cca]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

# Application specific settings (based on existing application.yml)
cca:
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKeyH2Development12345678901234567890}
      expiration: 3600000  # 1 hour
      refresh-expiration: 86400000  # 24 hours
