# Configurações para ambiente de PRODUÇÃO
spring:
  web:
    locale: pt_BR
    locale-resolver: fixed
  mvc:
    log-resolved-exception: true
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd'T'HH:mm:ss
    message-codes-resolver-format: POSTFIX_ERROR_CODE
    contentnegotiation:
      favor-parameter: false
      media-types:
        json: application/json;charset=UTF-8
        html: text/html;charset=UTF-8
        plain: text/plain;charset=UTF-8
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db.caracore.com.br}:${DB_PORT:5432}/${DB_NAME:cca_prod}?charSet=UTF8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Pool de conexões otimizado para produção
      maximum-pool-size: 25        # Máximo de conexões simultâneas
      minimum-idle: 10             # Mínimo de conexões ociosas
      connection-timeout: 30000    # Timeout para obter conexão (30s)
      idle-timeout: 600000         # Timeout para conexão ociosa (10min)
      max-lifetime: 1800000        # Tempo máximo de vida da conexão (30min)
      leak-detection-threshold: 60000  # Detectar vazamento de conexão (60s)
      pool-name: CCA-Production-Pool
      # Configurações de validação
      validation-timeout: 5000     # Timeout para validação (5s)
      connection-test-query: SELECT 1
      auto-commit: false           # Controle manual de transações
      # Configurações de inicialização
      connection-init-sql: "SET search_path TO public"
      # Configurações de performance
      register-mbeans: true        # Monitoramento JMX
      allow-pool-suspension: false
      # Configurações específicas para produção
      isolate-internal-queries: true
  
  jpa:
    hibernate:
      ddl-auto: validate  # NUNCA permitir alterações automáticas em produção
    show-sql: false  # SQL logs SEMPRE desabilitados em produção
    properties:
      hibernate:
        '[format_sql]': false
        '[use_sql_comments]': false
        '[generate_statistics]': false
        '[jdbc.batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
  
  # Cache habilitado e otimizado
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
  
  # DevTools DESABILITADO
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# Logging mínimo e seguro para produção
logging:
  level:
    root: WARN
    '[org.springframework.security]': ERROR
    '[org.springframework.web]': WARN
    '[com.caracore.cca]': INFO
    '[org.hibernate.SQL]': ERROR
    '[USER_ACTIVITY]': INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/cca/cca-application.log
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/cca/archived/cca-application-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      max-history: 90
      total-size-cap: 10GB
  
# Swagger DESABILITADO em produção por segurança
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Configurações específicas da aplicação para produção
cca:
  ambiente: producao
  debug-mode: false
  mock-external-services: false
  whatsapp:
    api-url: ${WHATSAPP_API_URL}
    api-key: ${WHATSAPP_API_KEY}
    enabled: true
    timeout: 30000
  email:
    smtp:
      host: ${SMTP_HOST}
      port: ${SMTP_PORT:587}
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      auth: true
      starttls: true
    from: ${EMAIL_FROM:noreply@caracore.com.br}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:3600000}  # 1 hora
    session:
      timeout: ${SESSION_TIMEOUT:1800}  # 30 minutos
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Todo dia às 2h
    retention-days: 30

# Configurações do reCAPTCHA para produção
recaptcha:
  enabled: ${RECAPTCHA_ENABLED:true}  # Habilitado obrigatoriamente em produção
  site-key: ${RECAPTCHA_SITE_KEY}  # OBRIGATÓRIO via variável de ambiente
  secret-key: ${RECAPTCHA_SECRET_KEY}  # OBRIGATÓRIO via variável de ambiente
  verify-url: ${RECAPTCHA_VERIFY_URL:https://www.google.com/recaptcha/api/siteverify}
  threshold: ${RECAPTCHA_THRESHOLD:0.7}  # Threshold mais restritivo para produção

# Configurações do servidor otimizadas para produção
server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true  # HTTPS obrigatório
        http-only: true
        same-site: strict
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 1024
  http2:
    enabled: true
  error:
    include-message: never  # Não expor detalhes de erro
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Monitoramento e métricas para produção
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never  # Não expor detalhes internos
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 9090  # Porta separada para métricas
    
# Configurações de segurança adicionais para produção
security:
  headers:
    frame: deny
    content-type: nosniff
    xss-protection: "1; mode=block"
    referrer-policy: strict-origin-when-cross-origin
