server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cca_db
    driver-class-name: org.postgresql.Driver
    username: cca_user
    password: cca_password
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
spring.sql.init.mode: never
# Para evitar execução dupla de scripts em ambiente de teste, descomente a linha acima se necessário.